version: "3"
services:
  postgres:
    image: postgres:13.10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - "postgres_datadir:/var/lib/postgresql/data"
    ports:
      - "65466:5432"
    expose:
      - "5432"


volumes:
  postgres_datadir: